version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

dockers_v2:
  - id: sml-exporter
    dockerfile: Dockerfile.goreleaser
    images:
      - databus23/sml-exporter
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
